name: 'Dependency Tree Diff'
description: 'Displays differences in the dependencies resulting from a pull request'
inputs:
  pr:
    description: 'The number of the PR to check dependencies for'
    required: true
  token:
    description: 'A GitHub token that can be used to authorise commenting on and labelling the pull requests'
    required: true
  deps-ok-label:
    description: 'Name of the label to add to pull requests that have no significant version changes'
    required: true
  deps-changed-label:
    description: 'Name of the label to add to pull requests that have a significant version change'
    required: true
  tool-change-mentions:
    description: 'GitHub user names in @mention format to be used in comments where versions changed'
  base-version-files:
    description: 'Files containing the base versions relative to $GITHUB_WORKSPACE'
    required: true
  new-version-files:
    description: 'Files containing the new versions relative to $GITHUB_WORKSPACE'
    required: true
runs:
  using: 'docker'
  # image: 'Dockerfile'
  image: 'docker://quay.io/kabirk/dep-tree-diff:latest'
  args:
    - ${{ inputs.pr }}
    - ${{ inputs.token }}
    - ${{ inputs.deps-ok-label }}
    - ${{ inputs.deps-changed-label }}
    - ${{ inputs.tool-change-mentions }}
    - ${{ inputs.base-version-files }}
    - ${{ inputs.new-version-files }}